# Generated by Django 5.1.5 on 2025-03-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercart',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
