# Generated by Django 5.1.5 on 2025-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_stripe_id_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('denied', 'Denied'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
